# Docs: https://github.com/azure/functions-action

name: Build and deploy .NET 8 Function App - batfn-crn-we-researcher-sand-02

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '9.0.x' 

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }} environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Explicitly build the right project file
      - name: Build and publish function project
        shell: pwsh
        run: |
          dotnet restore PatSnapProxy.csproj
          dotnet publish PatSnapProxy.csproj --configuration Release --output ./output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_86A88E2DD47449ECABCFD48789E1CE18 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5F8ED0D809A5427981577448D696ECE7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8EAE745DBDB5451E9ED098C1D4DDD8F3 }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'batfn-crn-we-researcher-sand-02'
          slot-name: 'Production'
          package: './output'
